project:
  type: website
  output-dir: ../docs

website:
  title: "Compartilhando"
  navbar:
    left:
      - text: Início
        href: index.html
      - text: "Conteúdos"
        menu:
          - text: "Fator de proporcionalidade da verossimilhança"
            href: page1.html
          - text: "Serie de Taylor"
            href: page2.html